FROM python:3.12

RUN pip install --no-cache-dir fastapi uvicorn
RUN pip install --no-cache-dir openai
RUN pip install --no-cache-dir ddtrace

ADD ./server.py .
CMD ["uvicorn", "server:app", "--host=0.0.0.0", "--port=8080"]
