FROM python:3.12-slim

# Server dependencies
RUN pip install --no-cache-dir fastapi==0.115.4 uvicorn==0.32.0

# Integration dependencies
RUN pip install --no-cache-dir openai==1.97.0 vertexai==1.71.1 google-genai==1.27.0 anthropic==0.63.0

# Install ddtrace here to ensure dependencies are installed in container
RUN pip install --no-cache-dir ddtrace

ADD ./server.py .
CMD ["python", "server.py"]
