# ARG OPENAI_VERSION
# ARG PYTHON_VERSION

FROM python:3.12

# FROM python:$PYTHON_VERSION

# RUN pip install openai==$OPENAI_VERSION

RUN pip install fastapi uvicorn
RUN pip install openai
RUN pip install ddtrace

ADD ./server.py .
CMD ["uvicorn", "server:app", "--host=0.0.0.0", "--port=8080"]
